import fs from "node:fs";
import path from "node:path";
import type { SolidityProof } from "../types";

export const BASE_TOKENS_PER_MINT = 50000;
export const MAX_MINTS = 10000;

type SnarkJs = {
  groth16: {
    fullProve: (
      input: Record<string, string>,
      wasmPath: string,
      zkeyPath: string
    ) => Promise<{ proof: unknown; publicSignals: string[] }>;
    exportSolidityCallData: (proof: unknown, publicSignals: string[]) => Promise<string> | string;
  };
};

const snarkjs = require("snarkjs") as SnarkJs;

export interface ProofResult {
  proof: SolidityProof;
  publicSignals: string[];
}

export async function generateProof(entropy: string, salt: string): Promise<ProofResult> {
  const wasmPath = path.resolve(process.cwd(), "circuits", "entropy.wasm");
  const zkeyPath = path.resolve(process.cwd(), "circuits", "entropy_final.zkey");

  ensureCircuitFile(wasmPath, "entropy.wasm");
  ensureCircuitFile(zkeyPath, "entropy_final.zkey");

  const { proof, publicSignals } = await snarkjs.groth16.fullProve({ entropy, salt }, wasmPath, zkeyPath);
  const calldata = await snarkjs.groth16.exportSolidityCallData(proof, publicSignals);

  return {
    proof: parseSolidityProof(calldata),
    publicSignals,
  };
}

function ensureCircuitFile(filePath: string, name: string): void {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing circuit artifact ${name}. Place it in backend/circuits before generating proofs.`);
  }
}

function parseSolidityProof(calldata: string): SolidityProof {
  const parsed = JSON.parse(`[${calldata}]`) as [string[], string[][], string[]];
  const [a, b, c] = parsed;

  if (!Array.isArray(a) || !Array.isArray(b) || !Array.isArray(c)) {
    throw new Error("Invalid Solidity calldata generated by snarkjs");
  }

  return {
    a: [a[0], a[1]],
    b: [
      [b[0][0], b[0][1]],
      [b[1][0], b[1][1]],
    ],
    c: [c[0], c[1]],
  };
}
